### ISSUE TITLE
You need to update the openinv API for the plugin to run on 1.21.1

### ISSUE THREAD

**Issue by thiagogebrimm** [Minebench/SyncInv#15]
### What is happening?

OpenInv has changed its API and needs to be updated in SyncInv to work in 1.21.1

### What did you expect to happen?

Should start the plugin correctly

### Version

latest

### Config

```YAML
N/A
```

### Server/system Version

1.21.1

### Log

```shell
N/A
```

### What other programs/plugins are you running?

N/A

**Comment by Phoenix616** [comment]
Already in progress in #12

**Comment by thiagogebrimm** [comment]
any eta to finish?

**Comment by Phoenix616** [comment]
> any eta to finish?
> 

I mean the PR is most likely working already, I just haven't gotten around to test it myself yet. Will probably merge it on the weekend as I plan to update my server soon.
