### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by msmanui** [Minebench/SyncInv#5]
Hi!

There is an issue between items sync when it has special enchantsments. For example when u put a HELMET and it apply extra heart, when u change of server it will remove the health, and if u try to put again the helmet it wont work anyway. This also applies with other custom enchants.

**Comment by Phoenix616** [comment]
Do you mean items with attributes? Or some custom functionality of another plugin? If so which plugin?

**Comment by msmanui** [comment]
> Do you mean items with attributes? Or some custom functionality of another plugin? If so which plugin?

 Basically, any plugin that applies extra hearts. I tested with "EliteEnchantments" and it happens.
 1. If you put a helmet/chestplate/leggings/boots in your slot armor it will apply extra hearts, right? If i go to server_nether it wont save me those hearts and it should. 
 2. If me, in the server overworld i put a helmet it will apply extra hearts and after that if i remove it from the armor slot, it wont remove the hearts. I tested this in another server with a normal survival and it will remove but somehow with invSync/serverdimensions it wont.
 
Feel free to test in the VPS. Do **/kit claim newvalkiria** and that kit cointains the helmet/chestplate/etc to test it yourself.

**Comment by Phoenix616** [comment]
As far as I can tell this has nothing to do with SyncInv but with that plugin not applying effects properly when a different plugin adds the items to those slots, they need to make sure to properly check for that and not only player interactions. The same bug would occur when any other plugin directly adds items to those slots. (E.g. via a kit plugin)

**Comment by msmanui** [comment]
> As far as I can tell this has nothing to do with SyncInv but with that plugin not applying effects properly when a different plugin adds the items to those slots, they need to make sure to properly check for that and not only player interactions. The same bug would occur when any other plugin directly adds items to those slots. (E.g. via a kit plugin)

I undertstand but this bug doesnt happen in a enviorment of one survival when changing between worlds.

**Comment by Phoenix616** [comment]
Because they are on the same server, yes which means they use the same inventory and enchantment plugin instance.

Syncing items between servers requires the items to be added to the inventory on the other server and the enchantment plugin doesn't detect that properly.

**Comment by msmanui** [comment]
> Because they are on the same server, yes which means they use the same inventory and enchantment plugin instance.
> 
> Syncing items between servers requires the items to be added to the inventory on the other server and the enchantment plugin doesn't detect that properly.


Okay so what should i tell him to add?

**Comment by Phoenix616** [comment]
They need to make sure that effects are applied (and removed) if anything (be it a player or plugin) changes the items in the slots.

**Comment by msmanui** [comment]
> They need to make sure that effects are applied (and removed) if anything (be it a player or plugin) changes the items in the slots.

We execute with a vanilla command and is still happening **/effect give User minecraft:health_boost**  and we had the effect for 30 seconds and two extra hearts, but when we teleport to server 2, it will remaing the seconds but the amount of health wont sync.

**Comment by 7wOv6ySCjo** [comment]
Same problem here. The plugin does not support custom size healt.

https://i.imgur.com/XNQLAlX.jpg

**Comment by Phoenix616** [comment]
Will be fixed once GitHub is stable again and allows me to actually push the fix...

**Comment by 7wOv6ySCjo** [comment]
> Will be fixed once GitHub is stable again and allows me to actually push the fix...

Nice work, congratulations for your plugin. It is the most efficient and complete on the market.

After this update there is a delay when applying the player's health whatever the scale is. Is it possible to try to fix this and leave it like the vanilla experience? In vanilla experience this delay does not exist, it is reflected immediately.
I can make a video showing this delay if you like.
