### ISSUE TITLE
Info to add compatibility with 1.17

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [Minebench/SyncInv#6]
Error: https://pastebin.com/j9aEigvn

```
> version
[01:26:42 INFO]: Checking version, please wait...
[01:26:43 INFO]: This server is running Tuinity version git-Tuinity-"8e7cc4d" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8e7cc4d on HEAD)
You are running the latest version
```
Also try with paper last dev build.

**Comment by Phoenix616** [comment]
The statistic `TOTAL_WORLD_TIME` clearly [exists](https://papermc.io/javadocs/paper/1.17/org/bukkit/Statistic.html#TOTAL_WORLD_TIME). Please make sure that your fork doesn't break compatibility with the Paper API.

**Comment by 7wOv6ySCjo** [comment]
> The statistic `TOTAL_WORLD_TIME` clearly [exists](https://papermc.io/javadocs/paper/1.17/org/bukkit/Statistic.html#TOTAL_WORLD_TIME). Please make sure that your fork doesn't break compatibility with the Paper API.

Tuinity is an official fork of Paper. Maintained by the Paper team.

I have tried the latest version of Paper 1.16.5 and the error [still occurs](https://pastebin.com/DUE8Berr).
Note: Is it because I'm coming from a server with Paper 1.17.1?

I upgraded one of my servers from 1.16.5 to 1.17.1 and then when I moved between servers this error appeared.
I know the plugin doesn't support: `java.lang.IllegalArgumentException: Newer version! Server downgrades are not supported!` but this was the error that appeared before I deactivated the "general-statistics" in SyncInv - config.yml. Maybe it's convenient that I'm reporting it. Besides I would like to know more about how the plugin works.

**Comment by Phoenix616** [comment]
Are you using the exact same server version on all your servers? That's pretty much the only thing that would definitly break it if that wasn't the case.

If it still doesn't work then please also test without any other plugins and with a fresh player. (Especially if you downgraded)

**Comment by 7wOv6ySCjo** [comment]
> Are you using the exact same server version on all your servers? That's pretty much the only thing that would definitly break it if that wasn't the case.
> 
> If it still doesn't work then please also test without any other plugins and with a fresh player. (Especially if you downgraded)

No, I have one server running paper 1.17 and another server running paper 1.16.
I will be leaving all servers 1.17 later so I guess at that point it would be wise to report any unexpected behaviour. Thank you.

**Comment by Phoenix616** [comment]
Yeah, sending data from different versions isn't really technically possible. 1.17 items don't exist on 1.16 after all.
